// Phylum 2: Subcultural — Batch 5 (Final)
// EMO & SCENE, ELECTRONIC & CLUB CULTURE, ROCKSTAR & PERFORMANCE, SKATE & SURF, POLITICAL

export const P02_BATCH5 = {

// ═══════════════════════════════════════════════════════════════════
// EMO & SCENE
// ═══════════════════════════════════════════════════════════════════

"Emo Aesthetic":{"summary":"The emotional hardcore-turned-mainstream aesthetic — side-swept fringe, skinny jeans, and the visual language of feelings made wearable.","era":"c.2001–2010; revival 2020s","mood":"Emotionally visible, fringe-swept, feelings-as-fashion","visual":"Long side-swept fringe covering one eye. Skinny jeans. Band T-shirt. Studded belt. Black eyeliner for all genders. Converse or Vans. The visual language of emotional vulnerability performed as subcultural identity.","garments":["Side-swept emo fringe","Skinny jeans","Band T-shirt","Studded belt","Black eyeliner"],"habitat":"Emo music communities, My Chemical Romance fan culture, emo revival events.","context":"Emo fashion evolved from hardcore punk's simplicity into a codified visual identity by 2004–05. The side-swept fringe became the definitive marker — a visual barrier between the wearer and the world.","rarity":"Common","see_also":["My Chemical Romance Aesthetic","Scene Aesthetic","Pop Punk Aesthetic"],"colors":["#1A1A1A Emo Black","#8B0000 Red","#FF6B6B Hot Pink","#FAF8F5 White"],"media":["My Chemical Romance: The Black Parade (2006) — music","The Perks of Being a Wallflower (2012) — film"]},

"Thursday Aesthetic":{"summary":"The earnest, poetry-reading, screaming-crying intersection of emo and post-hardcore — Geoff Rickly's literary intensity made visual.","era":"c.1999–2011","mood":"Literarily intense, post-hardcore earnest, poetry-screaming","visual":"Simple dark clothing. Less visually codified than later emo — more post-hardcore in influence. The aesthetic of someone who reads poetry and then screams it. Understated compared to MCR-era emo.","garments":["Simple dark T-shirt","Dark jeans","Understated casual shoes","Minimal accessories","Literary rather than fashion-focused"],"habitat":"Post-hardcore communities, Thursday fan culture, early 2000s emo heritage.","context":"Thursday represented emo before it became a visual brand — their aesthetic was earnest and literary rather than codified. Geoff Rickly's intensity was vocal and physical rather than sartorial.","rarity":"Rare","see_also":["Taking Back Sunday Aesthetic","Emo Aesthetic","Post-Punk Fashion"],"colors":["#1A1A1A Dark Black","#5B5B5B Grey","#8B0000 Blood Red","#FAF8F5 White"],"media":["Thursday: Full Collapse (2001) — music","Emo documentary — documentary"]},

"Taking Back Sunday Aesthetic":{"summary":"The Long Island emo-pop-punk visual identity — the specific early 2000s blend of emo sensitivity and pop-punk energy.","era":"c.2002–2007","mood":"Pop-emo energetic, Long Island-coded, studded-belt era","visual":"Tight band T-shirt. Studded belt. Lip ring. Straightened emo hair. The specific look of early 2000s emo-pop that filled Warped Tour stages.","garments":["Tight band T-shirt","Studded belt","Lip ring piercing","Straightened dark hair","Converse or Vans"],"habitat":"Warped Tour heritage, emo-pop communities, 2000s emo nostalgia.","context":"Taking Back Sunday represented the commercial peak of emo-pop — their aesthetic was more accessible than screamo, more emotionally coded than pop-punk. The studded belt era.","rarity":"Niche","see_also":["Emo Aesthetic","Fall Out Boy Aesthetic","Pop Punk Aesthetic"],"colors":["#1A1A1A Emo Black","#8B0000 Red","#FAF8F5 White","#5B5B5B Grey"],"media":["Taking Back Sunday: Tell All Your Friends (2002) — music","Warped Tour footage"]},

"My Chemical Romance Aesthetic":{"summary":"The theatrical, Black Parade-era, Gerard Way-led visual spectacle of MCR — emo elevated to rock opera, with matching uniforms and concept-album costumes.","era":"c.2002–2013; reunion 2019–present","mood":"Theatrically emo, concept-album-costumed, operatically dark","visual":"The Black Parade era: matching black marching-band uniforms with military details. Three Cheers era: red and black, Helena-era ties and vests. Danger Days era: colourful futuristic. Each album had a complete visual identity.","garments":["Black Parade marching uniform","Red-and-black Helena-era vest","Military-detailed jacket","Emo fringe with theatrical makeup","Concept-specific costume"],"habitat":"MCR fan communities, emo heritage, When We Were Young festival.","context":"My Chemical Romance treated each album as a visual concept — The Black Parade (2006) had matching military-band uniforms that elevated emo from bedroom subculture to arena spectacle. Gerard Way's art training showed.","rarity":"Niche","see_also":["Emo Aesthetic","Fall Out Boy Aesthetic","Bowie Aesthetic"],"colors":["#1A1A1A Parade Black","#8B0000 Helena Red","#FAF8F5 White","#D4AF37 Military Gold"],"media":["My Chemical Romance: The Black Parade (2006) — music","MCR: Life on the Murder Scene (2006) — documentary"]},

"Fall Out Boy Aesthetic":{"summary":"Pete Wentz's specific brand of emo-pop visual identity — eyeliner, hoodies, and the transition from basement shows to arena spectacle.","era":"c.2003–present","mood":"Eyeliner-pop, hoodie-coded, arena-emo","visual":"Heavy black eyeliner. Hoodie with band art. Tight jeans. Pete Wentz's specific combination of emo sensitivity and pop-punk attitude. Clandestine Industries brand clothing.","garments":["Heavy black eyeliner","Band hoodie","Tight dark jeans","Clandestine Industries piece","Sneakers"],"habitat":"Fall Out Boy fan communities, pop-emo heritage, arena emo culture.","context":"Fall Out Boy bridged emo and mainstream pop — Pete Wentz became a celebrity beyond music, and the band's visual evolution from basement emo to Infinity on High arena show tracked emo's commercial trajectory.","rarity":"Common","see_also":["Emo Aesthetic","My Chemical Romance Aesthetic","Pop Punk Aesthetic"],"colors":["#1A1A1A FOB Black","#D4AF37 Gold","#8B0000 Red","#FAF8F5 White"],"media":["Fall Out Boy: Live in Phoenix (2008) — music","MTV Cribs Pete Wentz — TV"]},

"Emo Revival":{"summary":"The 2010s–20s return to emo — Midwest emo bands, twinkly guitars, and a new generation discovering the emotional power of the side-swept fringe.","era":"c.2012–present","mood":"Nostalgically emo, twinkly-revived, new-generation emotional","visual":"Updated emo aesthetics — less theatrical than MCR era, more DIY. Midwest emo band T-shirts. Thrifted flannel. The aesthetic is rawer and less polished than 2000s emo.","garments":["Midwest emo band T-shirt","Thrifted flannel","Skinny or slim jeans","Simple sneakers","Less polished than 2000s emo"],"habitat":"Emo revival communities, basement shows, DIY emo venues.","context":"The Emo Revival (c.2012–present) returned to emo's DIY roots — bands like American Football's reunion, Tiny Moving Parts, and Mom Jeans represented a less theatrical, more musically focused emo.","rarity":"Niche","see_also":["Emo Aesthetic","Midwest Emo Aesthetic","Modern Emo"],"colors":["#1A1A1A Revival Black","#8B7355 Flannel Brown","#5B5B5B Grey","#FAF8F5 White"],"media":["American Football reunion footage — music","Emo revival documentary content"]},

"Modern Emo":{"summary":"Contemporary emo as it exists now — the aesthetic maintained and evolved by communities who never stopped being emo.","era":"c.2015–present","mood":"Continuously emo, evolved-maintained, still feeling","visual":"The emo aesthetic updated for the current moment — skinny jeans (or the debate about whether to go wider), band merch from both eras, eyeliner still present. The maintained subculture rather than the revival.","garments":["Updated skinny or slim jeans","New and vintage band T-shirts","Eyeliner maintained","Contemporary emo band merch","Black or dark clothing base"],"habitat":"Emo communities worldwide, emo nights, When We Were Young festival.","context":"Modern Emo represents the maintained subculture — people who have been emo continuously since 2004, plus newer adherents. It is a living tradition, not just a revival.","rarity":"Common","see_also":["Emo Aesthetic","Emo Revival","Emo Nite Aesthetic"],"colors":["#1A1A1A Emo Black","#8B0000 Red","#5B5B5B Grey","#FF6B6B Pink"],"media":["When We Were Young Festival — cultural","Emo Nite events — cultural"]},

"Midwest Emo Aesthetic":{"summary":"The flannel-and-math-rock visual culture of Midwest emo — American Football's house, twinkly guitars, and the specific aesthetic of Illinois basements.","era":"c.1995–present","mood":"Basement-twinkly, Illinois-coded, math-rock flannel","visual":"Flannel shirt. Simple jeans. The American Football house as visual icon. Less theatrical than East Coast emo — more flannel, more ordinary, more focused on the music than the look.","garments":["Flannel shirt","Simple blue jeans","Band T-shirt","Baseball cap","Ordinary sneakers"],"habitat":"Midwest emo communities, American Football fan culture, DIY basement venues.","context":"Midwest emo's visual identity is deliberately ordinary — the flannel and jeans of college-town Illinois. The American Football house (on the cover of their 1999 debut) became one of indie music's most photographed locations.","rarity":"Niche","see_also":["Emo Revival","Modern Emo","Indie Rock Aesthetic"],"colors":["#8B7355 Midwest Flannel","#1B4F72 Denim Blue","#FAF8F5 White","#5B5B5B Basement Grey"],"media":["American Football debut album art (1999) — music","Midwest emo documentary content"]},

"Scene Aesthetic":{"summary":"The neon-highlighted, MySpace-curated, maximally decorated youth aesthetic of the mid-2000s — brighter, louder, and more colourful than emo.","era":"c.2005–2010","mood":"Neon-maximal, MySpace-curated, attention-demanding","visual":"Bright-coloured hair extensions and streaks. Heavy eye makeup. Band T-shirts. Skinny jeans. Scene hair: voluminous, teased, with multiple colours. The aesthetic designed for MySpace profile photos.","garments":["Voluminous multi-coloured scene hair","Heavy eye makeup","Band T-shirt","Skinny jeans","Neon accessories"],"habitat":"MySpace era heritage, scene communities, Scene revival.","context":"Scene emerged from emo but was brighter, louder, and more visually competitive — the MySpace profile was the stage, and scene hair was the performance. The aesthetic required hours of daily maintenance.","rarity":"Niche","see_also":["Scene Queen","Emo Aesthetic","MySpace Era Fashion"],"colors":["#FF6B6B Neon Pink","#39FF14 Neon Green","#1A1A1A Black","#00BFFF Electric Blue"],"media":["MySpace scene archives — internet","Scene documentary content"]},

"Scene Queen":{"summary":"The maximally decorated, hair-extreme, MySpace-famous feminine Scene identity — the most visually labour-intensive youth aesthetic in internet history.","era":"c.2006–2010","mood":"Maximally decorated, hair-extreme, MySpace-famous","visual":"Scene hair at its most extreme — teased to impossible volume, multiple colours, extensions. Heavy raccoon-eye makeup. Neon accessories. Hello Kitty references. The look required hours of preparation for a single MySpace photo.","garments":["Maximum-volume scene hair","Raccoon-eye heavy makeup","Neon bow accessories","Hello Kitty references","Platform shoes"],"habitat":"MySpace heritage, scene queen communities, 2000s nostalgia.","context":"Scene Queens were MySpace's first influencers — accumulating tens of thousands of friends through their visual presentations. The labour involved in achieving the look was extraordinary and underappreciated.","rarity":"Rare","see_also":["Scene Aesthetic","MySpace Era Fashion","E-Girl"],"colors":["#FF6B6B Scene Pink","#1A1A1A Black","#39FF14 Neon Green","#D4AF37 Bow Gold"],"media":["MySpace scene queen archives — internet"]},

"Scene Revival":{"summary":"The 2020s TikTok return of Scene aesthetics — neon hair, raccoon eyes, and Gen Z discovering the most labour-intensive aesthetic of the 2000s.","era":"c.2021–present","mood":"TikTok-revived, nostalgia-neon, Gen Z scene","visual":"Scene hair recreated with modern tools. Updated raccoon-eye makeup. Neon colours. The 2000s Scene aesthetic filtered through TikTok's tutorial culture.","garments":["Revived scene hair","Updated raccoon-eye makeup","Neon accessories","Scene band merch","Platform boots"],"habitat":"TikTok, Scene revival communities, 2000s nostalgia events.","context":"Scene Revival on TikTok demonstrates how internet aesthetics can be revived on new platforms — Gen Z discovering Scene through archived MySpace photos and recreating it with modern tools and tutorials.","rarity":"Niche","see_also":["Scene Aesthetic","Y2K Revival","Emo Revival"],"colors":["#FF6B6B Revival Pink","#39FF14 Neon Green","#1A1A1A Black","#00BFFF Blue"],"media":["TikTok scene revival content — social media"]},

"Y2K Scene":{"summary":"The intersection of Y2K nostalgia and Scene revival — early 2000s maximalism meets neon scene hair.","era":"c.2022–present","mood":"Y2K-scene hybrid, nostalgia-doubled, internet-fused","visual":"Y2K fashion elements (low-rise, butterfly clips) combined with Scene elements (neon hair, heavy eye makeup). A hybrid of two 2000s aesthetics that were originally separate.","garments":["Y2K low-rise jeans","Scene-coloured hair","Butterfly clips with neon accents","Heavy eye makeup","Platform shoes"],"habitat":"TikTok aesthetic crossover, Y2K-Scene hybrid communities.","context":"Y2K Scene fuses two parallel 2000s aesthetics that rarely overlapped at the time — Y2K pop and Scene emo. The internet makes combinations that geography once prevented.","rarity":"Emerging","see_also":["Scene Revival","Y2K Revival","McBling Goth"],"colors":["#FF6B6B Pink","#87CEEB Y2K Blue","#39FF14 Scene Green","#D4AF37 Gold"],"media":["TikTok hybrid aesthetic content — social media"]},

"Scenecore":{"summary":"The harder, more aggressive edge of Scene — closer to metalcore and deathcore, with more brutal music and more extreme visual presentation.","era":"c.2006–2012","mood":"Aggressively scene, metalcore-edged, breakdown-coded","visual":"Scene hair but darker. More band merch from heavier bands (Bring Me the Horizon, Asking Alexandria). Stretched earlobes. More piercings. The visual edge where Scene met metalcore's brutality.","garments":["Scene hair (darker)","Metalcore band T-shirt","Stretched earlobes","Multiple piercings","Skinny jeans with drops"],"habitat":"Metalcore-scene crossover, heavy music communities.","context":"Scenecore represented Scene's heavier edge — where the aesthetic met metalcore's musical brutality. Bands like early Bring Me the Horizon had scene-influenced members who dressed the part.","rarity":"Niche","see_also":["Scene Aesthetic","Emo Aesthetic","Nu Metal Aesthetic"],"colors":["#1A1A1A Black","#8B0000 Blood Red","#FF6B6B Pink","#C0C0C0 Silver"],"media":["Bring Me the Horizon early footage — music"]},

"Soft Emo":{"summary":"The gentler, less aggressive, more romanticised version of emo — sad but pretty, dark but soft.","era":"c.2015–present","mood":"Sadly pretty, gently dark, romanticised emo","visual":"Softer version of emo styling. Less eyeliner, more natural. Dark clothing but softer fabrics. The emo fringe maintained but softer. Sad-girl rather than angry-boy energy.","garments":["Soft dark clothing","Gentle emo fringe","Minimal eyeliner","Soft dark layers","Simple dark accessories"],"habitat":"Soft emo communities, TikTok emo content, gentle alternative.","context":"Soft Emo represents emo's gentler contemporary expression — sadness without aggression, darkness without theatre. It overlaps significantly with the broader sad-girl internet aesthetic.","rarity":"Common","see_also":["Pastel Emo","Soft Goth","Sadgirl Aesthetic"],"colors":["#2C2C2C Soft Black","#C185A0 Sad Pink","#5B5B5B Gentle Grey","#B0C4DE Soft Blue"],"media":["TikTok soft emo content — social media"]},

"Pastel Emo":{"summary":"Emo's pastel variant — pastel colours with emo silhouettes and emotional coding, like Pastel Goth's optimistic cousin.","era":"c.2015–present","mood":"Pastel-sad, candy-emo, gently emotional","visual":"Pastel-coloured emo styling. Pastel hair with emo fringe. Soft colours with emotional coding. The collision of candy and sadness.","garments":["Pastel-coloured emo outfit","Pastel-dyed emo fringe","Soft-coloured band merch","Pastel accessories","Platform shoes in pastel"],"habitat":"Pastel emo communities, TikTok, Instagram.","context":"Pastel Emo follows the same internet logic as Pastel Goth — taking a dark subculture's visual forms and replacing the darkness with candy colours while maintaining the emotional register.","rarity":"Niche","see_also":["Soft Emo","Pastel Goth","Emo Kawaii"],"colors":["#F5C6CB Pastel Pink","#B0C4DE Pastel Blue","#D4EA9B Pastel Green","#C185A0 Lavender"],"media":["TikTok pastel emo — social media"]},

"Emo Kawaii":{"summary":"The fusion of emo emotional coding with Japanese kawaii cute culture — sad but cute, dark but adorable.","era":"c.2015–present","mood":"Sadly cute, emo-kawaii fused, dark-adorable","visual":"Kawaii accessories (bows, plushies) with emo styling. Japanese cute culture merged with Western emotional hardcore. Dark colours with cute elements.","garments":["Kawaii bow with emo outfit","Plushie accessories","Dark clothing with cute details","Emo fringe with kawaii elements","Platform shoes"],"habitat":"Emo kawaii communities, Japanese-Western aesthetic fusion.","context":"Emo Kawaii represents the ongoing fusion of Japanese and Western subcultural aesthetics — a process that has been happening since Visual Kei first influenced Western goth in the 1990s.","rarity":"Niche","see_also":["Pastel Emo","Pastel Goth","Decora"],"colors":["#1A1A1A Emo Black","#FF6B6B Kawaii Pink","#87CEEB Cute Blue","#D4AF37 Bow Gold"],"media":["Emo kawaii content — social media"]},

"Garage Band Aesthetic":{"summary":"The deliberately rough, rehearsal-room dress of the garage band — whatever you were wearing when you started playing.","era":"c.1960s–present","mood":"Rehearsal-rough, deliberately unpolished, whatever-you-wore","visual":"Whatever you were wearing. Jeans and T-shirt. The deliberate absence of a designed aesthetic — the garage band dresses like people, not performers. The aesthetic IS the lack of aesthetic.","garments":["Whatever jeans you own","Band or plain T-shirt","Whatever shoes you wore today","No designed look","Rehearsal-room natural"],"habitat":"Garage rehearsal spaces, small venue culture, DIY music communities.","context":"The garage band aesthetic is the zero-degree of subcultural fashion — no design, no intention, just people making music in the clothes they already own. It is the most democratic dress code in music.","rarity":"Common","see_also":["DIY Band Aesthetic","Indie Rock Aesthetic","Lo-Fi Music Aesthetic"],"colors":["#8B7355 Whatever Brown","#1B4F72 Jeans Blue","#FAF8F5 Tee White","#5B5B5B Grey"],"media":["School of Rock (2003) — film","Garage band documentary — documentary"]},

"DIY Band Aesthetic":{"summary":"The self-screen-printed, hand-drawn-merch, touring-on-$5-a-day visual culture of the DIY music community.","era":"c.1980s–present","mood":"Self-printed, hand-drawn, economically toured","visual":"Self-screen-printed band T-shirts. Hand-drawn flyers as aesthetic. Touring van as habitat. The visual culture of bands that do everything themselves — the merch is as DIY as the music.","garments":["Self-screen-printed T-shirt","Hand-drawn logo patches","Touring-worn clothing","DIY accessories","Van-life road wear"],"habitat":"DIY venues, basement shows, zine fairs, independent music communities.","context":"DIY band culture produces its own visual identity through economic necessity — when you can't afford a designer, you design yourself. The hand-drawn flyer and screen-printed tee are art forms in their own right.","rarity":"Niche","see_also":["Garage Band Aesthetic","DIY Punk","Zine Culture Aesthetic"],"colors":["#1A1A1A Print Black","#FAF8F5 Tee White","#8B0000 Ink Red","#5B5B5B Screen Grey"],"media":["Turn It Around (2017) — documentary","DIY punk and indie documentaries"]},

"Bedroom Pop Fashion":{"summary":"The laptop-produced, soft-focus, aesthetically curated dress of bedroom pop — the visual equivalent of lo-fi recording.","era":"c.2015–present","mood":"Laptop-intimate, soft-focus, aesthetically bedroom","visual":"Soft, casual, intimate clothing. Oversized T-shirts. Comfortable layers. The aesthetic of someone who records music in their bedroom and dresses accordingly — intimate, unpretentious, and slightly dreamy.","garments":["Oversized soft T-shirt","Comfortable layers","Simple casual trousers","Bedroom-casual styling","Unpretentious accessories"],"habitat":"Bedroom pop communities, lo-fi music culture, Spotify playlist aesthetic.","context":"Bedroom pop fashion mirrors its production method — intimate, low-key, and made at home. Clairo, Rex Orange County, and Boy Pablo each dressed in ways that communicated the same intimacy as their music.","rarity":"Common","see_also":["Lo-Fi Music Aesthetic","Indie Rock Aesthetic","Soft Girl Aesthetic"],"colors":["#B0C4DE Bedroom Blue","#F5C6CB Soft Pink","#FAF8F5 White","#8B7355 Warm Brown"],"media":["Clairo discography — music","Rex Orange County discography — music"]},

"Emo Nite Aesthetic":{"summary":"The specific visual culture of Emo Nite events — the 2010s–20s club-night format where adults dress in their teenage emo best and sing along.","era":"c.2014–present","mood":"Nostalgically dressed-up, sing-along emo, adult-teenage","visual":"Adults recreating their teenage emo looks — the side fringe, the eyeliner, the band T-shirts. Some maintained the look; others are putting it on for one night. The aesthetic of collective nostalgia.","garments":["Recreated emo fringe","Vintage band T-shirt","Eyeliner (possibly rusty)","Skinny jeans","Converse"],"habitat":"Emo Nite events globally, emo nostalgia club nights.","context":"Emo Nite LA (founded 2014) created a global format — club nights where adults sing along to MCR, Fall Out Boy, and Paramore. The fashion is collective nostalgia made physical.","rarity":"Common","see_also":["Emo Aesthetic","Modern Emo","Emo Revival"],"colors":["#1A1A1A Nite Black","#8B0000 Red","#FF6B6B Pink","#FAF8F5 White"],"media":["Emo Nite LA documentation — cultural"]},

// ═══════════════════════════════════════════════════════════════════
// ELECTRONIC & CLUB CULTURE
// ═══════════════════════════════════════════════════════════════════

"Ballroom Aesthetic":{"summary":"The spectacular, competitive, category-walking visual culture of the Ball scene — realness, performance, and the house system as family.","era":"c.1960s–present, New York","mood":"Competitively spectacular, house-family coded, category-walking","visual":"Category-specific: Executive Realness (corporate suit), Femme Queen (feminine beauty), Butch Queen (masculine presentation), Runway (model walk). Each category has specific visual requirements. The aesthetic is competitive excellence.","garments":["Category-specific outfit","Executive Realness suit","Femme Queen gown","Runway walk outfit","House-colour accessories"],"habitat":"Ballroom events, Ball culture worldwide, house communities.","context":"Ball culture began in 1960s Harlem as a space for Black and Latinx LGBTQ+ people to compete in categories reflecting the mainstream world that excluded them. Paris Is Burning (1990) documented it. FX's Pose (2018–21) brought it to mainstream awareness.","rarity":"Niche","see_also":["Vogue Fashion","House Mother Aesthetic","Drag Queen Aesthetic"],"colors":["#D4AF37 Ball Gold","#8B0000 House Red","#FAF8F5 Realness White","#1A1A1A Category Black"],"media":["Paris Is Burning (1990) — documentary","Pose (TV series, 2018–21) — TV"]},

"Vogue Fashion":{"summary":"The runway-walk, hand-performance, competitive dance fashion of the vogue scene — where dance and fashion are inseparable art forms.","era":"c.1960s–present","mood":"Runway-performing, hand-striking, competitively fierce","visual":"Whatever the category demands, worn with attitude and movement skill. The outfit must facilitate the dance — arms free for hand performance, legs for dips. Fashion as performance art.","garments":["Category-appropriate outfit","Movement-facilitating design","Statement accessories","Heels for runway categories","Body-conscious silhouette"],"habitat":"Vogue balls, ballroom events, vogue dance communities worldwide.","context":"Vogue emerged from the Ball scene as a competitive dance form — the fashion IS the dance. Madonna's 'Vogue' (1990) brought it to mainstream awareness but the culture existed for decades before and continues far beyond it.","rarity":"Niche","see_also":["Ballroom Aesthetic","House Mother Aesthetic","Madonna Aesthetic"],"colors":["#D4AF37 Vogue Gold","#1A1A1A Black","#C0C0C0 Silver","#8B0000 Red"],"media":["Paris Is Burning (1990) — documentary","Pose (TV series) — TV","Madonna: Vogue (1990) — music video"]},

"House Mother Aesthetic":{"summary":"The specific authority dress of the House Mother in Ball culture — the matriarch who leads, judges, and protects her house family.","era":"c.1970s–present","mood":"Matriarchally authoritative, house-leading, community-anchoring","visual":"Elegant, authoritative dress. Often more refined than competitive — the House Mother doesn't need to win; she judges. Quality clothing that communicates experience and authority.","garments":["Elegant authoritative outfit","Quality refined accessories","House-colour elements","Matriarchal presence","Sophisticated styling"],"habitat":"Ball culture, house leadership, ballroom community events.","context":"The House Mother is Ball culture's central figure — she provides family, guidance, and shelter to LGBTQ+ youth rejected by biological families. Her dress reflects authority earned through community service.","rarity":"Rare","see_also":["Ballroom Aesthetic","Vogue Fashion","Drag Queen Aesthetic"],"colors":["#D4AF37 Authority Gold","#1A1A1A Refined Black","#8B0000 House Red","#C0C0C0 Silver"],"media":["Pose (TV series) — TV","Paris Is Burning (1990) — documentary"]},

"Chicago House Aesthetic":{"summary":"The specific visual culture of Chicago house music — warehouse parties, Frankie Knuckles's Warehouse, and the dress of the original four-on-the-floor.","era":"c.1983–1990, Chicago","mood":"Warehouse-born, four-on-the-floor, Black-queer-joyous","visual":"Club wear for warehouse parties. Dance-functional clothing. The aesthetic of dressing for all-night dancing in spaces that were not designed as nightclubs. Bold colours and self-expression.","garments":["Dance-functional club wear","Bold self-expression","Warehouse-appropriate clothing","Layered for temperature change","Statement accessories"],"habitat":"Chicago house heritage, Warehouse legacy, Black LGBTQ+ club culture.","context":"Chicago house music was born in Frankie Knuckles's Warehouse — a primarily Black, primarily gay space. The fashion was dance-functional self-expression in improvised venues.","rarity":"Extinct","see_also":["Detroit Techno Aesthetic","UK Rave Aesthetic","Ballroom Aesthetic"],"colors":["#D4AF37 Warehouse Gold","#1A1A1A Black","#FF6B6B Bold Pink","#87CEEB Electric Blue"],"media":["Pump Up the Volume (1990) — documentary","The Warehouse legacy documentaries"]},

"Detroit Techno Aesthetic":{"summary":"The futurist, Afrofuturist-adjacent, deliberately austere visual identity of Detroit techno — the Belleville Three dressed for the future.","era":"c.1985–present, Detroit","mood":"Afrofuturistically austere, Detroit-industrial, future-coded","visual":"Clean, often dark clothing. Minimal accessories. Futurist references. The aesthetic of people making music that sounded like Detroit's abandoned factories transformed into optimism.","garments":["Clean dark clothing","Minimal accessories","Futurist-referenced pieces","Simple practical wear","Understated quality"],"habitat":"Detroit techno heritage, Movement festival, techno worldwide.","context":"Detroit techno's originators — Juan Atkins, Derrick May, Kevin Saunderson — dressed with futurist intention. The music imagined a technological future; the fashion was equally forward-looking.","rarity":"Niche","see_also":["Chicago House Aesthetic","Berlin Techno Fashion","Afrofuturism"],"colors":["#1A1A1A Techno Black","#C0C0C0 Machine Silver","#5B5B5B Detroit Grey","#D4AF37 Future Gold"],"media":["High Tech Soul (2006) — documentary","God Said Give 'Em Drum Machines (2023) — documentary"]},

"UK Rave Aesthetic":{"summary":"The neon, smiley-faced, baggy-trousered visual explosion of British rave culture — the Second Summer of Love made wearable.","era":"c.1988–1995, Britain","mood":"Neon-ecstatic, smiley-faced, PLUR-coded","visual":"Baggy jeans or dungarees. Neon colours. Smiley face motif. Glow sticks. Whistles. Oversized T-shirts. Bucket hats. The aesthetic of dancing in a field from sunset to sunrise.","garments":["Baggy neon trousers","Smiley face T-shirt","Bucket hat","Glow sticks","Whistle"],"habitat":"UK rave heritage, Acid House events, free party communities.","context":"The UK rave explosion of 1988–92 produced one of the most recognisable youth fashion moments in British history. The Criminal Justice Act 1994 (targeting 'repetitive beats') was a direct response to the culture.","rarity":"Niche","see_also":["Acid House Fashion","Second Summer of Love","PLUR Aesthetic"],"colors":["#FFFF00 Smiley Yellow","#39FF14 Neon Green","#FF6B6B Neon Pink","#00BFFF Electric Blue"],"media":["Human Traffic (1999) — film","24 Hour Party People (2002) — film"]},

"Acid House Fashion":{"summary":"The specific 1988 Acid House moment — smiley faces, Shoom-era ecstasy culture, and the most euphoric fashion moment in British youth history.","era":"c.1987–1990, Britain","mood":"Euphorically smiley, Shoom-era, ecstasy-joyous","visual":"The yellow smiley face as the definitive symbol. Baggy clothing for dancing. Day-Glo colours. Dungarees. Bandanas. The aesthetic of euphoria — everything bright, loose, and movement-ready.","garments":["Yellow smiley face T-shirt","Baggy dungarees","Day-Glo colours","Bandana","Oversized for movement"],"habitat":"Acid House heritage, Shoom club history, 1988 cultural memory.","context":"Danny Rampling's Shoom club (1987) and the smiley face T-shirt together created the visual identity of Acid House. The smiley was borrowed from a 1960s American design — it was never copyrighted and became rave's universal symbol.","rarity":"Extinct","see_also":["UK Rave Aesthetic","Second Summer of Love","Chicago House Aesthetic"],"colors":["#FFFF00 Acid Smiley","#1A1A1A Black","#39FF14 Day-Glo Green","#FF6B6B Day-Glo Pink"],"media":["24 Hour Party People (2002) — film","Beats (2019) — film"]},

"Second Summer of Love":{"summary":"The 1988–89 UK cultural moment when acid house, ecstasy, and open-air raving briefly created a genuine youth utopia — and dressed accordingly.","era":"c.1988–1989, Britain","mood":"Utopianly euphoric, open-air, briefly perfect","visual":"The perfect synthesis of acid house and outdoor festival — brightly coloured, loose, functional for 12 hours of dancing. Bandanas, whistles, glow sticks. The aesthetic of genuine collective euphoria.","garments":["Brightly coloured loose clothing","Bandana","Whistle","Glow sticks","Festival-functional layers"],"habitat":"1988 Summer of Love heritage, acid house history.","context":"The Second Summer of Love (1988–89) was a genuine cultural moment — the collision of MDMA, acid house music, and open-air venues created a brief period of real utopian community. The fashion expressed genuine joy.","rarity":"Extinct","see_also":["Acid House Fashion","UK Rave Aesthetic","Festival Folk"],"colors":["#FFFF00 Summer Yellow","#39FF14 Love Green","#FF6B6B Love Pink","#87CEEB Summer Blue"],"media":["24 Hour Party People (2002) — film","Human Traffic (1999) — film"]},

"Haçienda Aesthetic":{"summary":"The specific visual culture of Manchester's Haçienda nightclub — Factory Records' design ethos applied to clubbing.","era":"c.1982–1997, Manchester","mood":"Factory-designed, Mancunian iconic, design-club","visual":"Peter Saville's graphic design applied to the club space. Ben Kelly's interior design. The specific Mancunian mix of acid house, indie, and football casual that the Haçienda fostered.","garments":["Casual-smart clubwear","Mancunian casual influence","Factory Records aesthetic","Acid house and indie mixed","Quality sportswear"],"habitat":"Manchester music heritage, Haçienda cultural history, Factory Records legacy.","context":"The Haçienda (1982–97) was Factory Records' nightclub — it lost money for years before acid house made it Britain's most famous venue. Peter Saville's design gave it the most distinctive visual identity of any nightclub.","rarity":"Extinct","see_also":["Madchester Fashion","Acid House Fashion","Joy Division Aesthetic"],"colors":["#D4AF37 Haçienda Yellow","#1A1A1A Factory Black","#5B5B5B Concrete","#FAF8F5 White"],"media":["24 Hour Party People (2002) — film","The Haçienda: How Not to Run a Club — book"]},

"Madchester Fashion":{"summary":"The baggy-jeaned, tie-dyed, psychedelic-casual dress of the Madchester music scene — Stone Roses, Happy Mondays, and Manchester's indie-dance revolution.","era":"c.1988–1992, Manchester","mood":"Baggily psychedelic, Mancunian-dancing, indie-rave fused","visual":"Baggy flared jeans. Tie-dye or psychedelic prints. Bucket hat. The specific Mancunian fusion of indie guitar music and acid house — you dressed to dance to both.","garments":["Baggy flared jeans","Tie-dye or psychedelic print","Bucket hat","Casual oversized top","Dance-ready trainers"],"habitat":"Manchester music heritage, Stone Roses and Happy Mondays fan culture.","context":"Madchester merged indie rock and acid house — the Stone Roses were guitar gods who made you dance, the Happy Mondays were ravers who had guitar solos. The fashion fused both cultures.","rarity":"Extinct","see_also":["Haçienda Aesthetic","Britpop Aesthetic","Acid House Fashion"],"colors":["#D4AF37 Madchester Gold","#8B0000 Rose Red","#4A7C59 Psychedelic Green","#87CEEB Tie-Dye Blue"],"media":["24 Hour Party People (2002) — film","Stone Roses: Made of Stone (2013) — documentary"]},

"PLUR Aesthetic":{"summary":"Peace Love Unity Respect — the utopian rave philosophy expressed through kandi bracelets, bright colours, and the visual language of radical kindness.","era":"c.1990–present","mood":"Utopianly kind, kandi-wearing, radical-peaceful","visual":"Kandi bracelets (handmade bead bracelets) traded between ravers. Bright neon colours. Tutus and wings. The visual expression of rave's utopian philosophy — radical kindness and community.","garments":["Handmade kandi bracelets","Bright neon colours","Tutu or costume element","Wings or costume accessories","Comfortable dance clothing"],"habitat":"Rave and EDM communities, kandi trading culture, festival communities.","context":"PLUR was coined by DJ Frankie Bones after a 1993 New York rave. Kandi bracelets are handmade and traded through a specific handshake ritual. The aesthetic expresses genuine communitarian values.","rarity":"Niche","see_also":["Kandi Aesthetic","EDM Festival Aesthetic","UK Rave Aesthetic"],"colors":["#FF6B6B PLUR Pink","#39FF14 PLUR Green","#FFFF00 PLUR Yellow","#00BFFF PLUR Blue"],"media":["Rave documentaries","PLUR culture documentation"]},

"Kandi Aesthetic":{"summary":"The handmade bead-bracelet culture of rave — each bracelet made by hand, traded through specific ritual, and worn in stacks to the elbow.","era":"c.1990s–present","mood":"Handmade-traded, bead-stacked, ritually exchanged","visual":"Arms covered in handmade bead bracelets. Perler bead creations. Neon colours. Each bracelet has personal meaning — made for or traded with specific people through the PLUR handshake.","garments":["Stacked kandi bracelets","Perler bead creations","Neon bead accessories","Handmade bead cuffs","Kandi necklaces"],"habitat":"EDM festivals, rave communities, kandi making and trading communities.","context":"Kandi culture is one of rave's most distinctive traditions — the handmaking and trading of beaded bracelets as an act of community building. Each bracelet has a story.","rarity":"Niche","see_also":["PLUR Aesthetic","EDM Festival Aesthetic","Rave Fashion 1990s"],"colors":["#FF6B6B Kandi Pink","#39FF14 Kandi Green","#FFFF00 Kandi Yellow","#00BFFF Kandi Blue"],"media":["Kandi culture documentation — cultural"]},

"Jungle / Drum and Bass Aesthetic":{"summary":"The London, late-night, bass-heavy visual culture of jungle and drum and bass — tracksuits, trainers, and the sound of the city at 3am.","era":"c.1991–present, London","mood":"Bassline-heavy, London-nocturnal, tracksuit-ready","visual":"Quality tracksuits. Clean trainers. Simple, functional clothing for all-night dancing. Less visually spectacular than rave — more London, more nocturnal, more focused on the bass.","garments":["Quality tracksuit","Clean trainers","Simple dark clothing","Minimal accessories","Dance-functional layers"],"habitat":"Drum and bass events, jungle heritage, London bass music culture.","context":"Jungle emerged from London's Black British community — the fashion was street-smart, bass-focused, and less visually spectacular than rave. It was about the music and the sound system, not the costume.","rarity":"Niche","see_also":["UK Rave Aesthetic","UK Club Aesthetic","Drill Aesthetic"],"colors":["#1A1A1A Night Black","#5B5B5B Urban Grey","#D4AF37 Gold","#2C5530 Jungle Green"],"media":["Jungle Fever documentary — documentary","Pirates of the Airwaves — documentary"]},

"Berlin Techno Fashion":{"summary":"The all-black, minimal, Berghain-adjacent dress code of Berlin's techno scene — darkness as philosophy, the body as medium.","era":"c.1990–present, Berlin","mood":"All-black minimal, body-focused, Berghain-coded","visual":"All black. Minimal. Body-conscious or leather/fetish-influenced. The specific Berlin combination of austere minimalism and physical intensity. Dressing for a club with no mirrors and no phones.","garments":["All-black minimal outfit","Leather or harness element","Body-conscious base layer","Combat boots","Minimal accessories"],"habitat":"Berlin techno clubs, Berghain adjacent culture, dark techno events worldwide.","context":"Berlin techno fashion is inseparable from the city's club culture — the no-phone, no-photo policies mean the fashion exists in the moment. The all-black dress code is both aesthetic choice and practical requirement for dark rooms.","rarity":"Niche","see_also":["Berghain Aesthetic","Minimal Techno Fashion","Industrial Goth"],"colors":["#1A1A1A Berlin Black","#2C2C2C Dark Leather","#5B5B5B Concrete","#C0C0C0 Metal"],"media":["Berlin Calling (2008) — film","B-Movie: Lust & Sound in West-Berlin (2015) — documentary"]},

"Berghain Aesthetic":{"summary":"The specific dress code of the world's most famous nightclub — all black, no phones, no fashion brands, and the aesthetic of being selected by the door.","era":"c.2004–present, Berlin","mood":"Door-selected, phone-free, supremely dark","visual":"All black. No visible brand logos. Leather, PVC, or minimal black. The specific aesthetic of a club where the door policy is as famous as the music. Sven Marquardt's face tattoos as the club's visual identity.","garments":["All-black unbranded outfit","Leather or PVC elements","Minimal body-conscious base","Combat or industrial boots","No visible logos"],"habitat":"Berghain, Berlin, and its global cultural influence.","context":"Berghain's door policy (run by Sven Marquardt) created a specific fashion pressure — people dress specifically to get in. The no-phone policy means the fashion exists only in memory. The aesthetic has influenced dark fashion globally.","rarity":"Rare","see_also":["Berlin Techno Fashion","Minimal Techno Fashion","Industrial Goth"],"colors":["#1A1A1A Berghain Black","#2C2C2C Leather","#5B5B5B Concrete","#C0C0C0 Metal"],"media":["Berlin Calling (2008) — film","Berghain documentary — documentary"]},

"Minimal Techno Fashion":{"summary":"The stripped-back, function-over-form, deliberately austere dress of minimal techno culture — where less is everything.","era":"c.1995–present","mood":"Stripped-back, deliberately austere, sonically minimal","visual":"Simple black clothing. No decoration. The visual equivalent of minimal techno's stripped-back sound — nothing unnecessary. Function over form, darkness over display.","garments":["Simple black T-shirt","Plain dark trousers","Minimal black shoes","No accessories","No decoration"],"habitat":"Minimal techno events, Berlin and European techno culture.","context":"Minimal techno fashion reflects the music's philosophy — strip everything to the essential. The aesthetic is less a fashion choice than a philosophical position about what is necessary.","rarity":"Niche","see_also":["Berlin Techno Fashion","Berghain Aesthetic","Normcore"],"colors":["#1A1A1A Minimal Black","#2C2C2C Dark","#5B5B5B Grey","#FAF8F5 White"],"media":["Minimal techno documentation — music"]},

"UK Club Aesthetic":{"summary":"The broader visual culture of British clubbing — from superclubs to underground, the dress of going out in British cities.","era":"c.1990s–present, Britain","mood":"Going-out ready, British-club-coded, nightlife-dressed","visual":"The specific British club aesthetic — smart-casual to dressed-up depending on venue. Heels and short dresses for women. Smart shirts for men. The door policy as fashion pressure.","garments":["Smart-casual to dressed-up","Heels (women)","Smart shirt (men)","Going-out quality accessories","Club-appropriate outfit"],"habitat":"British nightlife, club culture across UK cities.","context":"British clubbing has its own fashion ecology — door policies create specific dress pressures, regional variations exist (London vs Manchester vs Glasgow), and the pre-drinks-to-taxi wardrobe is a specific British genre.","rarity":"Common","see_also":["UK Rave Aesthetic","Berghain Aesthetic","Going Out Aesthetic"],"colors":["#1A1A1A Club Black","#D4AF37 Gold","#8B0000 Red","#C0C0C0 Silver"],"media":["Human Traffic (1999) — film","Skins (TV series) — TV"]},

"Raver / Rave Culture":{"summary":"The sustained, community-maintained global rave culture — from 1988's fields to today's festivals, the perpetual culture of dancing all night.","era":"c.1988–present, global","mood":"Perpetually dancing, community-maintained, all-night","visual":"Bright colours and neon. Comfortable dance clothing. Kandi. Glow accessories. The sustained visual vocabulary of a culture that has existed for over 35 years and shows no sign of stopping.","garments":["Comfortable dance clothing","Neon and bright colours","Kandi bracelets","Glow accessories","Festival-functional layers"],"habitat":"Rave events globally, EDM festivals, underground rave communities.","context":"Rave culture has been continuous since 1988 — it adapted through commercial phases (superclubs), underground phases (free parties), and festival phases (EDM). The visual culture evolved but maintained its core vocabulary.","rarity":"Common","see_also":["UK Rave Aesthetic","PLUR Aesthetic","EDM Festival Aesthetic"],"colors":["#FF6B6B Rave Pink","#39FF14 Rave Green","#FFFF00 Rave Yellow","#00BFFF Rave Blue"],"media":["Human Traffic (1999) — film","Rave culture documentaries"]},

"EDM Festival Aesthetic":{"summary":"The mainstream festival fashion of the EDM era — flower crowns, body glitter, and the commercialisation of rave culture for stadium events.","era":"c.2010–present","mood":"Festival-commercialised, glitter-coded, stadium-rave","visual":"Body glitter. Flower crowns. Crop tops and high-waisted shorts. Festival totems. Face gems. The mainstream festival wardrobe that commercialised rave's visual vocabulary for Instagram.","garments":["Body glitter","Flower crown","Crop top and high-waisted shorts","Face gems","Festival totem"],"habitat":"Tomorrowland, Ultra, Electric Daisy Carnival, major EDM festivals.","context":"EDM Festival Aesthetic represents rave culture's commercial moment — the visual vocabulary of underground rave (neon, glitter, costumes) scaled to stadium-sized festivals and Instagram documentation.","rarity":"Common","see_also":["Coachella Fashion","PLUR Aesthetic","Raver / Rave Culture"],"colors":["#FF6B6B Festival Pink","#D4AF37 Glitter Gold","#39FF14 Neon Green","#00BFFF Electric Blue"],"media":["Tomorrowland footage — cultural","Ultra Music Festival footage"]},

"Coachella Fashion":{"summary":"The specific fashion ecosystem of Coachella festival — flower crowns, crochet, and the festival that became a fashion show.","era":"c.2010–present, Indio, California","mood":"Fashion-festival, Instagram-prime, California-curated","visual":"Coachella-specific fashion: crochet, fringe, flower crowns, boho elements, statement sunglasses. The festival became as much a fashion event as a music event — brands set up activations, influencers attend for content.","garments":["Crochet or fringe top","Flower crown","Statement sunglasses","Boho-festival dress","Coachella-specific fashion piece"],"habitat":"Coachella Valley Music and Arts Festival, Indio California.","context":"Coachella became fashion's festival — by the mid-2010s, brand activations and influencer content had eclipsed the music as the reason many people attended. The 'Coachella outfit' became its own fashion category.","rarity":"Common","see_also":["EDM Festival Aesthetic","Festival Folk","Boho Feminine"],"colors":["#D4AF37 Desert Gold","#C1440E Fringe Orange","#87CEEB California Blue","#FAF8F5 White"],"media":["Coachella festival documentation — cultural"]},

"Hyperpop Fashion":{"summary":"The maximally digital, neon-coloured, deliberately artificial visual culture of hyperpop — where pop is pushed past its own breaking point.","era":"c.2018–present","mood":"Maximally digital, neon-artificial, post-pop","visual":"Neon and digital colours. Deliberately artificial and plastic. Platform boots. Digital-influenced makeup. The visual equivalent of music that sounds like pop put through a blender — everything louder, brighter, more.","garments":["Neon-coloured clothing","Platform boots","Digital-influenced makeup","Deliberately plastic or artificial materials","Maximally bright accessories"],"habitat":"Hyperpop communities, PC Music fan culture, 100 gecs audience.","context":"Hyperpop fashion is deliberately artificial — it rejects natural materials and organic aesthetics in favour of plastic, neon, and digital. It is anti-cottagecore by design.","rarity":"Niche","see_also":["PC Music Aesthetic","E-Girl","Cyber Goth"],"colors":["#FF6B6B Hyper Pink","#39FF14 Hyper Green","#00BFFF Hyper Blue","#FFFF00 Hyper Yellow"],"media":["100 gecs discography — music","Charli XCX: how i'm feeling now (2020) — music"]},

"PC Music Aesthetic":{"summary":"The deliberately plastic, hyper-glossy, post-ironic visual world of the PC Music label — A.G. Cook's vision of pop as conceptual art.","era":"c.2013–present, London","mood":"Hyper-glossy, post-ironic, conceptually plastic","visual":"Hyper-glossy, deliberately artificial visual identity. CGI avatars. Plastic colours. The visual language of A.G. Cook and SOPHIE's vision of pop music as conceptual art about pop music.","garments":["Hyper-glossy outfit","Plastic or PVC elements","Digital-art-influenced styling","Deliberately artificial materials","Conceptual fashion piece"],"habitat":"PC Music fan culture, experimental pop communities.","context":"PC Music's aesthetic was explicitly conceptual — the music, the visuals, and the fashion were all commentary on pop culture's artificiality. SOPHIE's tragic death in 2021 marked the loss of the movement's most radical visual and sonic artist.","rarity":"Rare","see_also":["Hyperpop Fashion","E-Girl","Digital Club Wear"],"colors":["#FF6B6B Gloss Pink","#87CEEB Plastic Blue","#C0C0C0 Chrome","#FAF8F5 Gloss White"],"media":["SOPHIE discography — music","PC Music label visual archives"]},

"Digital Club Wear":{"summary":"The post-pandemic, virtually-influenced, screen-first club fashion — clothing designed to look as good on screen as in person.","era":"c.2020–present","mood":"Screen-first, virtually-influenced, post-pandemic","visual":"Clothing that reads well on camera. Reflective or holographic materials. Bold, high-contrast colours. The aesthetic of a generation that experienced club culture through screens before venues.","garments":["Reflective or holographic material","High-contrast bold colours","Camera-friendly design","Futuristic accessories","Platform shoes"],"habitat":"Post-pandemic club culture, digital fashion communities, virtual events.","context":"Digital Club Wear emerged from the pandemic's virtual rave culture — people dressed for streams and Instagram live before returning to physical venues. The screen-first approach persisted.","rarity":"Emerging","see_also":["Hyperpop Fashion","Berghain Aesthetic","Metaverse Fashion"],"colors":["#C0C0C0 Holographic","#FF6B6B Neon Pink","#00BFFF Electric Blue","#D4AF37 Reflective Gold"],"media":["Virtual rave documentation — cultural"]},

"Psytrance / Trance Festival Fashion":{"summary":"The UV-reactive, fractal-patterned, full-moon-party visual culture of psytrance and trance festivals.","era":"c.1990s–present","mood":"Fractal-patterned, UV-reactive, full-moon coded","visual":"UV-reactive clothing with fractal or psychedelic patterns. Natural materials mixed with neon. Loose flowing garments for dancing. The aesthetic of outdoor trance parties in Goa, Thailand, and global festivals.","garments":["UV-reactive fractal-pattern clothing","Loose flowing dance garments","Natural-neon material mix","Psychedelic print","Comfortable festival wear"],"habitat":"Psytrance festivals, Goa, full moon parties, Boom Festival.","context":"Psytrance fashion draws from its origins in Goa, India — the mix of Indian fabrics with UV-reactive materials reflects the culture's fusion of Eastern spiritual influences with Western electronic music.","rarity":"Niche","see_also":["UK Rave Aesthetic","EDM Festival Aesthetic","PLUR Aesthetic"],"colors":["#39FF14 UV Green","#7B68EE Fractal Purple","#FF6B6B Neon Pink","#D4AF37 Goa Gold"],"media":["Boom Festival footage — cultural","Goa trance documentary"]},

"Hardstyle / Gabber Aesthetic":{"summary":"The extreme, high-BPM, shaved-head, Australian-flag-wearing visual culture of gabber and hardstyle — Europe's hardest dance music.","era":"c.1992–present, Netherlands","mood":"Extremely hard, high-BPM, shaved-head aggressive","visual":"Shaved or very short hair. Gabber tracksuits. Australian brand (Australian by L'Alpina) tracksuits as specific cultural marker. Nike Air Max TN as the shoe. The aesthetic of the hardest possible dance music.","garments":["Australian brand tracksuit","Nike Air Max TN","Shaved or very short hair","Simple aggressive clothing","Hardcore event merch"],"habitat":"Thunderdome, Defqon.1, Dominator, Dutch hardcore events.","context":"Gabber emerged from Rotterdam in the early 1990s as the hardest form of electronic dance music. The Australian tracksuit became its specific visual marker — a cheap Italian brand adopted as subcultural uniform by Dutch ravers.","rarity":"Niche","see_also":["UK Rave Aesthetic","Aggrotech Aesthetic","Hardstyle / Gabber Aesthetic"],"colors":["#1A1A1A Gabber Black","#D4AF37 Gold","#8B0000 Thunderdome Red","#FAF8F5 White"],"media":["Thunderdome footage — cultural","Gabber documentary"]},

"Dubstep / EDM Underground":{"summary":"The underground electronic bass music visual culture — hood-up, minimal, and the dress of clubs too dark to see in.","era":"c.2005–present","mood":"Hood-up, bass-dark, underground-minimal","visual":"Dark hoodies. Minimal dark clothing. The aesthetic of clubs so dark you can barely see what anyone is wearing — the music is the point, not the visual.","garments":["Dark hoodie","Minimal dark clothing","Comfortable bass-music clothing","Simple trainers","Hood up"],"habitat":"Underground bass music events, dark club culture, dubstep communities.","context":"Underground electronic bass culture deliberately strips visual spectacle — the clubs are dark, the music is the experience. The hoodie-up aesthetic communicates focus on sound over sight.","rarity":"Niche","see_also":["Berlin Techno Fashion","Minimal Techno Fashion","Drum and Bass"],"colors":["#1A1A1A Bass Black","#2C2C2C Hood Dark","#5B5B5B Underground Grey","#C0C0C0 Speaker Silver"],"media":["Underground bass music documentation"]},

// ═══════════════════════════════════════════════════════════════════
// ROCKSTAR & PERFORMANCE
// ═══════════════════════════════════════════════════════════════════

"Jimi Hendrix Aesthetic":{"summary":"The most spectacularly dressed guitarist in rock history — military jackets, headbands, and psychedelic colour that matched the music.","era":"c.1966–1970","mood":"Psychedelically spectacular, military-subverted, guitar-genius","visual":"Military jackets in velvet or brocade. Headband. Scarves tied at neck, wrist, and guitar. Ruffled shirts. Bell-bottoms. Rings on every finger. The aesthetic of someone whose clothing was as revolutionary as their guitar playing.","garments":["Military velvet jacket","Silk headband","Ruffled shirt","Bell-bottom trousers","Rings on every finger"],"habitat":"Hendrix fan culture, psychedelic rock heritage, guitar hero history.","context":"Hendrix dressed to match his music — explosive, colourful, and unlike anything before. His military jacket at Monterey Pop (1967) became one of rock's most iconic garments.","rarity":"Rare","see_also":["Rockstar Aesthetic","Led Zeppelin Aesthetic","Glam Rock"],"colors":["#7B68EE Hendrix Purple","#8B0000 Psychedelic Red","#D4AF37 Gold","#2C5530 Military Green"],"media":["Monterey Pop (1968) — documentary","Jimi Hendrix documentary — documentary"]},

"Rockstar Aesthetic":{"summary":"The universal visual code of the rock star — leather, attitude, and the performance of being the most important person in any room.","era":"c.1960s–present","mood":"Leather-attituded, room-commanding, stage-living","visual":"Leather jacket. Tight trousers. Statement accessories. Sunglasses indoors. The aesthetic of someone who lives on stage — everything slightly too much, slightly too loud, slightly too confident.","garments":["Leather jacket","Tight trousers","Sunglasses indoors","Statement jewellery","Boots with heel"],"habitat":"Rock music culture worldwide, backstage areas, rock bars.","context":"The Rockstar Aesthetic is one of the most persistent visual identities in popular culture — from Little Richard through Jagger to Harry Styles, the code evolves but the attitude persists.","rarity":"Common","see_also":["Rolling Stones Aesthetic","Led Zeppelin Aesthetic","Glam Rock"],"colors":["#1A1A1A Leather Black","#8B0000 Rock Red","#D4AF37 Gold","#C0C0C0 Silver"],"media":["Almost Famous (2000) — film","This Is Spinal Tap (1984) — film"]},

"Rolling Stones Aesthetic":{"summary":"Mick Jagger's lips and Keith Richards's scarves — the 60-year visual identity of the world's greatest rock and roll band.","era":"c.1962–present","mood":"Permanently cool, lips-and-scarves, eternal","visual":"Mick: tight trousers, open shirt, physical energy. Keith: skull ring, headband, scarves, cigarette. The Stones' look has barely changed in 60 years — it just got more expensive.","garments":["Tight trousers (Jagger)","Skull ring (Richards)","Headband and scarves","Open-necked shirt","Boots"],"habitat":"Rolling Stones fan culture, rock heritage worldwide.","context":"The Rolling Stones have maintained a consistent visual identity longer than any other act in rock history. Keith Richards's skull ring, headband, and scarves are as recognisable as any brand logo.","rarity":"Niche","see_also":["Rockstar Aesthetic","Led Zeppelin Aesthetic","Jimi Hendrix Aesthetic"],"colors":["#8B0000 Stones Red","#1A1A1A Stones Black","#D4AF37 Gold","#FAF8F5 White"],"media":["Gimme Shelter (1970) — documentary","Crossfire Hurricane (2012) — documentary"]},

"Led Zeppelin Aesthetic":{"summary":"The heavy, mystical, Viking-scaled rock excess of Led Zeppelin — Robert Plant's open shirt and Jimmy Page's dragon suit.","era":"c.1968–1980","mood":"Mystically heavy, Viking-scaled, stadium-massive","visual":"Robert Plant: open-to-navel shirt, golden curled hair, tight jeans. Jimmy Page: dragon-embroidered suit, occult symbols, violin bow. The aesthetic of rock music at its most physically massive.","garments":["Open-to-navel shirt","Dragon-embroidered suit","Tight bell-bottom jeans","Occult symbol accessories","Golden long hair"],"habitat":"Led Zeppelin fan culture, classic rock heritage.","context":"Led Zeppelin dressed for stadium scale — Plant's golden mane and Page's dragon suit were visible from the back of the arena. Their visual excess matched their sonic excess.","rarity":"Rare","see_also":["Rockstar Aesthetic","Jimi Hendrix Aesthetic","Glam Rock"],"colors":["#D4AF37 Zeppelin Gold","#1A1A1A Black","#8B0000 Crimson","#2C5530 Dragon Green"],"media":["The Song Remains the Same (1976) — film","Led Zeppelin documentary — documentary"]},

"Arena Rock Fashion":{"summary":"The stadium-scaled, fog-machine-lit, deliberately spectacular dress of arena rock — designed to be visible from row ZZ.","era":"c.1975–present","mood":"Stadium-visible, fog-lit, deliberately spectacular","visual":"Everything oversized for arena visibility. Stage costumes rather than street clothes. Pyrotechnics-safe materials. The aesthetic of performance at scale — you need to read from 200 feet away.","garments":["Stage-scale costume","Pyrotechnics-safe materials","High-visibility design","Arena-scaled accessories","Performance-specific footwear"],"habitat":"Arena rock concerts, stadium tours, rock spectacle events.","context":"Arena rock fashion exists at a different scale from other music fashion — everything is designed to communicate to thousands of people simultaneously. KISS, Iron Maiden, and U2 each solved this differently.","rarity":"Niche","see_also":["Rockstar Aesthetic","Glam Metal","KISS"],"colors":["#D4AF37 Pyro Gold","#8B0000 Stage Red","#C0C0C0 Fog Silver","#1A1A1A Black"],"media":["KISS concert footage — music","Iron Maiden live footage — music"]},

"Hair Band Aesthetic":{"summary":"Specifically the hair-as-identity subset of arena rock — where the band name is less important than the collective hairstyle.","era":"c.1983–1991","mood":"Hair-identical, Aqua Net-bonded, collectively coiffed","visual":"The band as collective hairstyle. Matching or complementary enormous hair. Tight clothing secondary to hair maintenance. The aesthetic where four or five men in a band spent more time on their hair than their music.","garments":["Matching enormous hair","Tight spandex","Leopard print","Bandanas","Cowboy boots"],"habitat":"1980s rock heritage, Sunset Strip nostalgia, hair metal revival events.","context":"Hair Band is the subset of glam metal where the collective hairstyle WAS the brand identity — Poison, Warrant, and Cinderella were visually interchangeable to outsiders but distinct to fans.","rarity":"Extinct","see_also":["Glam Metal","Arena Rock Fashion","Rockstar Aesthetic"],"colors":["#D4AF37 Hairspray Gold","#FF6B6B Hot Pink","#1A1A1A Black","#C0C0C0 Silver"],"media":["The Decline of Western Civilization Part II (1988) — documentary"]},

"NME Aesthetic":{"summary":"The specific visual culture of NME (New Musical Express) front-cover bands — the British music press as fashion arbiter.","era":"c.1980s–2018, Britain","mood":"NME-featured, British-indie, press-photo-coded","visual":"The specific look of being an NME front-cover band — jeans, band T-shirt or leather jacket, the specific British indie combination that the magazine amplified and codified.","garments":["Leather or denim jacket","Band T-shirt","Skinny jeans","Converse or boots","British indie styling"],"habitat":"NME heritage, British indie music press culture.","context":"NME was the definitive British music fashion arbiter for decades — being on the cover meant your look was copied. The magazine's shift to digital (2018) ended an era of print-driven music fashion.","rarity":"Niche","see_also":["Indie Rock Aesthetic","Britpop Aesthetic","Strokes Aesthetic"],"colors":["#8B0000 NME Red","#1A1A1A Black","#FAF8F5 White","#D4AF37 Cover Gold"],"media":["NME archive covers — print","Live Forever (2003) — documentary"]},

"Downtown Girl":{"summary":"The 2021 TikTok aesthetic blending indie rock, Tumblr, and New York cool — vinyl records, coffee shops, and the romanticisation of indie culture.","era":"c.2021–present","mood":"Indie-romanticised, vinyl-carrying, coffee-shop cool","visual":"Oversized vintage band T-shirt. Leather or denim jacket. Mini skirt or mom jeans. Vinyl record as accessory. Coffee cup. The TikTok romanticisation of indie rock lifestyle.","garments":["Vintage band T-shirt","Leather jacket","Mini skirt or mom jeans","Vinyl record accessory","Dr Martens"],"habitat":"TikTok, Downtown Girl aesthetic communities, indie-romanticised fashion.","context":"Downtown Girl emerged on TikTok as a romanticisation of indie rock culture — the aesthetic packages record-store-visiting and coffee-shop-sitting into a visual identity. It's lifestyle aspiration as aesthetic.","rarity":"Common","see_also":["Indie Rock Aesthetic","Tumblr Grunge","Alt Girl Aesthetic"],"colors":["#1A1A1A Vinyl Black","#8B7355 Leather Brown","#5B5B5B Coffee Grey","#8B0000 Record Red"],"media":["TikTok Downtown Girl trend — social media"]},

"Bedroom Pop Aesthetic":{"summary":"The intimate, lo-fi, home-recorded visual identity of bedroom pop — fairy lights, soft focus, and the aesthetic of making music in your room.","era":"c.2015–present","mood":"Intimately lo-fi, fairy-lit, bedroom-recorded","visual":"Soft lighting (fairy lights). Casual intimate clothing. The aesthetic of the bedroom as creative studio — not a polished production space but a personal, intimate, slightly messy room.","garments":["Casual intimate clothing","Soft comfortable layers","Simple accessories","Bedroom-appropriate dress","Unpretentious styling"],"habitat":"Bedroom pop communities, lo-fi music culture, intimate venue performances.","context":"Bedroom Pop Aesthetic mirrors its production method — music made alone in bedrooms, dressed in whatever you were wearing. The aesthetic is intimacy without performance.","rarity":"Common","see_also":["Lo-Fi Music Aesthetic","Bedroom Pop Fashion","Indie Rock Aesthetic"],"colors":["#F5C6CB Fairy Light Pink","#B0C4DE Soft Blue","#FAF8F5 Warm White","#D4AF37 Fairy Gold"],"media":["Clairo: Diary 001 (2018) — music","Boy Pablo discography — music"]},

"Lo-Fi Music Aesthetic":{"summary":"The deliberately low-fidelity, tape-hiss, warm-grain visual and musical aesthetic — where imperfection IS the beauty.","era":"c.2010s–present","mood":"Tape-warm, grain-beautiful, imperfection-embracing","visual":"Warm, slightly blurred imagery. VHS or film-grain filters. Vintage equipment as props. The aesthetic of deliberate lo-fi — where the warmth of imperfection is the entire point.","garments":["Vintage casual clothing","Warm comfortable layers","Headphones as accessory","Simple retro-influenced pieces","Deliberately unpretentious"],"habitat":"Lo-fi music communities, lo-fi hip-hop stream culture, anime study-girl aesthetic.","context":"Lo-Fi Aesthetic extended beyond music into a complete visual identity — the lo-fi hip-hop YouTube streams with the anime study girl became one of the internet's most enduring visual formats.","rarity":"Common","see_also":["Bedroom Pop Aesthetic","Retro Tech Aesthetic","Vaporwave"],"colors":["#8B7355 Tape Warm","#C185A0 Lo-Fi Rose","#B0C4DE Grain Blue","#D4AF37 Vinyl Gold"],"media":["Lo-fi hip-hop streams — internet","Nujabes discography — music"]},

// ═══════════════════════════════════════════════════════════════════
// SKATE & SURF CULTURE
// ═══════════════════════════════════════════════════════════════════

"Z-Boys Aesthetic":{"summary":"The Dogtown, 1970s, swimming-pool-skating visual origin of modern skateboard culture — short shorts, Vans, and the original lords of the empty pool.","era":"c.1975–1980, Venice Beach, California","mood":"Dogtown original, pool-skating, California radical","visual":"Short shorts. Knee pads. Vans or canvas shoes. Tan skin. Bleached hair. The specific 1970s California aesthetic of the Zephyr team — kids from the wrong side of the tracks inventing a culture.","garments":["Short athletic shorts","Vans deck shoes","Knee and elbow pads","Zephyr team T-shirt","Sun-bleached hair"],"habitat":"Venice Beach heritage, Dogtown cultural history, skateboarding origins.","context":"The Z-Boys (Zephyr Competition Team) invented modern skateboarding in the empty swimming pools of drought-era 1970s Venice Beach. Their aesthetic was the foundation of everything skateboard fashion became.","rarity":"Extinct","see_also":["Skater Aesthetic","California Surf","Thrasher Aesthetic"],"colors":["#87CEEB Venice Blue","#D4AF37 Sun Gold","#FAF8F5 White","#8B7355 Tan"],"media":["Lords of Dogtown (2005) — film","Dogtown and Z-Boys (2001) — documentary"]},

"Skate Punk":{"summary":"The intersection of skateboarding and punk rock — Thrasher magazine, hardcore bands, and the aesthetic that gave skating its attitude.","era":"c.1980–present","mood":"Punk-skating, half-pipe aggressive, Thrasher-coded","visual":"Thrasher magazine T-shirt. Vans or skate shoes. Ripped jeans. Punk band T-shirts. The aesthetic of skaters who listen to punk and punks who skate — the cultures have been intertwined since the early 1980s.","garments":["Thrasher magazine T-shirt","Vans skate shoes","Ripped jeans","Punk band T-shirt","Skate-branded hoodie"],"habitat":"Skate parks, punk shows, Thrasher magazine culture.","context":"Skateboarding and punk rock merged in the early 1980s — bands like Suicidal Tendencies and JFA bridged the cultures. Thrasher magazine was the visual document of this merger.","rarity":"Niche","see_also":["Skater Aesthetic","Thrasher Aesthetic","Pop Punk Aesthetic"],"colors":["#1A1A1A Punk Black","#8B0000 Thrasher Red","#FAF8F5 White","#D4AF37 Flame Gold"],"media":["Thrasher magazine archives — print","Suicidal Tendencies footage — music"]},

"Skater Aesthetic":{"summary":"The universal visual code of skateboard culture — Vans, oversized tees, and the most globally consistent youth fashion of the last 40 years.","era":"c.1980–present, global","mood":"Board-carrying, Vans-wearing, globally consistent","visual":"Skate shoes (Vans, Nike SB, Etnies). Oversized or relaxed T-shirt. Cargo or baggy trousers. Beanie or cap. The skateboard as both vehicle and fashion accessory.","garments":["Vans or skate shoes","Oversized T-shirt","Cargo or baggy trousers","Beanie or cap","Skateboard"],"habitat":"Skate parks globally, skate shops, skate brand culture.","context":"Skateboard fashion is one of the most globally consistent youth aesthetics — a skater in Tokyo, Lagos, and São Paulo will share the same basic visual vocabulary. The culture transcends language.","rarity":"Common","see_also":["Thrasher Aesthetic","Street Skate Fashion","Streetwear Culture"],"colors":["#1A1A1A Skate Black","#FAF8F5 White","#8B0000 Red","#D4AF37 Gold"],"media":["Mid90s (2018) — film","Tony Hawk's Pro Skater (game) — cultural"]},

"Thrasher Aesthetic":{"summary":"The specific Thrasher magazine-associated visual identity — the flame logo, the attitude, and the magazine that IS skateboard culture.","era":"c.1981–present","mood":"Flame-logoed, magazine-defined, authenticity-guarding","visual":"Thrasher flame logo T-shirt or hoodie. The magazine's visual language applied to the body. Authenticity debates: wearing Thrasher without skating is contentious.","garments":["Thrasher flame logo T-shirt","Thrasher hoodie","Skate shoes","Ripped jeans","Skater casual"],"habitat":"Skate culture, Thrasher magazine readership, skate-fashion crossover.","context":"Thrasher magazine (founded 1981) is the Bible of skateboard culture. Its flame logo became one of the most recognisable brand marks in youth culture. The debate about non-skaters wearing Thrasher is perpetual.","rarity":"Common","see_also":["Skater Aesthetic","Skate Punk","Streetwear Culture"],"colors":["#D4AF37 Thrasher Flame","#8B0000 Thrasher Red","#1A1A1A Black","#FAF8F5 White"],"media":["Thrasher magazine — print","Thrasher King of the Road — video series"]},

"Street Skate Fashion":{"summary":"The contemporary urban skateboard fashion that bridges skating and streetwear — Supreme, Palace, and the board as luxury accessory.","era":"c.2000–present","mood":"Streetwear-skate, Supreme-coded, urban-riding","visual":"Supreme or Palace branded pieces. Quality skate shoes (Nike SB Dunks). Oversized or relaxed fit. The merger of skate culture with streetwear commerce — the board as both tool and brand accessory.","garments":["Supreme or Palace piece","Nike SB Dunks","Oversized hoodie","Relaxed-fit trousers","Quality cap"],"habitat":"Urban skate spots, Supreme stores, streetwear-skate crossover.","context":"Street Skate Fashion represents skateboarding's full commercialisation — Supreme sells for thousands at resale, Nike SB Dunks are collected as art objects. The culture's anti-corporate origins coexist awkwardly with its commercial present.","rarity":"Common","see_also":["Skater Aesthetic","Streetwear Culture","Sneakerhead Aesthetic"],"colors":["#8B0000 Supreme Red","#1A1A1A Black","#FAF8F5 White","#D4AF37 Gold"],"media":["Supreme documentary — documentary","Cherry (2014) — skate film"]},

"Skate Girl":{"summary":"The feminine expression of skate culture — Vans, oversized tees, and women claiming space in a historically masculine-coded subculture.","era":"c.2000–present","mood":"Space-claiming, board-carrying, femininely skating","visual":"Oversized skate brand T-shirt. Vans Old Skool. Relaxed jeans or skate trousers. The aesthetic of women who actually skate, distinct from the fashion adoption of skate brand clothing.","garments":["Oversized skate T-shirt","Vans Old Skool","Relaxed jeans","Skate brand hoodie","Actual skateboard"],"habitat":"Skate parks, women's skate communities, skate girl events.","context":"Women's skateboarding has historically been marginalised — Skate Girl aesthetic represents both the genuine culture and the ongoing fight for equal space in skate parks and skate media.","rarity":"Niche","see_also":["Skater Femme","Skater Aesthetic","Tomboy Aesthetic"],"colors":["#1A1A1A Skate Black","#FAF8F5 White","#FF6B6B Pink","#8B7355 Board Brown"],"media":["Skate Kitchen (2018) — film","Betty (TV series) — TV"]},

"Skater Femme":{"summary":"The specifically feminine, fashion-forward interpretation of skate culture — skate brands worn with feminine styling.","era":"c.2015–present","mood":"Femininely fashion-forward, skate-styled, board-optional","visual":"Skate brands styled with feminine elements. Oversized tee with skirt. Vans with dresses. The fashion interpretation of skate culture's wardrobe by women who may or may not skate.","garments":["Skate brand T-shirt with skirt","Vans styled femininely","Oversized hoodie dress","Skate-feminine hybrid","Board optional"],"habitat":"Skater femme fashion communities, skate-fashion crossover.","context":"Skater Femme represents the feminine fashion adoption of skate culture — distinct from Skate Girl (which implies actual skating), it is the skate wardrobe styled for feminine presentation.","rarity":"Common","see_also":["Skate Girl","Skater Aesthetic","Tomboy Aesthetic"],"colors":["#1A1A1A Skate Black","#FF6B6B Femme Pink","#FAF8F5 White","#8B7355 Vans Gum"],"media":["Betty (TV series) — TV","Skate Kitchen (2018) — film"]},

"Skate Streetwear":{"summary":"The full merger of skateboarding and streetwear culture — where the board and the brand are equally important.","era":"c.2010–present","mood":"Brand-board merged, hype-skating, fully commercial","visual":"Supreme, Palace, Stüssy worn as complete outfits. Limited-edition skate shoes collected as art. The full commercial integration of skate and streetwear cultures.","garments":["Supreme full outfit","Limited-edition skate shoes","Palace piece","Stüssy vintage","Quality skatewear brand"],"habitat":"Streetwear-skate crossover, hype culture, resale markets.","context":"Skate Streetwear is where skateboarding's $50 billion commercial value lives — the brands, the drops, the resale market. The culture's DIY origins are distant but still referenced.","rarity":"Common","see_also":["Streetwear Culture","Supreme Aesthetic","Sneakerhead Aesthetic"],"colors":["#8B0000 Supreme Red","#1A1A1A Black","#FAF8F5 White","#D4AF37 Gold"],"media":["Streetwear-skate crossover documentation"]},

"Skate Luxe":{"summary":"The high-fashion interpretation of skateboard aesthetics — when luxury brands put wheels on their handbags and skaters wear Prada.","era":"c.2017–present","mood":"Luxury-skating, high-fashion-boarded, paradoxically premium","visual":"Luxury brands incorporating skate elements. Prada and Louis Vuitton skate collaborations. High-fashion skatewear. The paradox of $1,000 skate shoes.","garments":["Luxury brand skate collaboration","High-fashion skatewear","Premium skate shoes","Designer skate accessories","Luxury-casual skate hybrid"],"habitat":"Fashion weeks, luxury-skate collaborations, high-end skatewear.","context":"Skate Luxe represents skateboarding's full absorption into luxury fashion — a trajectory from Z-Boys' $10 Vans to Louis Vuitton skate shoes that would have been incomprehensible to the Dogtown crew.","rarity":"Niche","see_also":["Skate Streetwear","Designer Streetwear","Luxury Streetwear"],"colors":["#D4AF37 Luxury Gold","#1A1A1A Black","#C0C0C0 Silver","#8B7355 Board"],"media":["Louis Vuitton skate collaboration — fashion"]},

"Sneakerhead Aesthetic":{"summary":"The collector, authenticator, and cultural community built around athletic shoe collecting — where sneakers are art, investment, and identity.","era":"c.1985–present","mood":"Collector-obsessive, authentication-coded, shoe-as-art","visual":"The shoes are the outfit's centrepiece — everything else is styled to display them. Shorts or cropped trousers to show full shoe. Colour-coordinated outfit to match sneaker. The shoe as the primary fashion statement.","garments":["Centrepiece collector sneaker","Outfit styled around shoes","Shorts or cropped trousers","Colour-matched accessories","Sneaker-display clothing"],"habitat":"Sneaker conventions, StockX, GOAT, sneakerhead communities.","context":"Sneaker culture is a $79 billion global market. The collector community authenticates, values, and trades shoes like art. Some sneakers sell for over $100,000 at auction.","rarity":"Common","see_also":["Streetwear Culture","Hip-Hop Luxury","Skate Streetwear"],"colors":["#8B0000 Jordan Red","#FAF8F5 White","#1A1A1A Black","#87CEEB University Blue"],"media":["Sneakerheadz (2015) — documentary","Air (2023) — film"]},

"Streetwear Culture":{"summary":"The global, multi-billion-dollar fashion ecosystem that grew from skate, surf, and hip-hop — now the dominant youth fashion paradigm worldwide.","era":"c.1990–present, global","mood":"Globally dominant, hype-driven, culturally foundational","visual":"Graphic T-shirts, hoodies, sneakers, and caps as the foundation. Brand-conscious but subcultural in origin. The visual vocabulary that now dominates global youth fashion.","garments":["Graphic hoodie","Quality sneakers","Branded cap","Oversized T-shirt","Streetwear-branded piece"],"habitat":"Global youth culture, streetwear communities, drop culture.","context":"Streetwear went from subcultural expression to dominant global fashion paradigm — it now generates more revenue than traditional fashion in many markets. Every luxury house now has a streetwear strategy.","rarity":"Common","see_also":["Sneakerhead Aesthetic","Designer Streetwear","Hip-Hop Luxury"],"colors":["#1A1A1A Street Black","#FAF8F5 White","#8B0000 Red","#D4AF37 Gold"],"media":["Fresh Dressed (2015) — documentary","Streetwear documentation — cultural"]},

"Surf Aesthetic":{"summary":"The universal visual code of surf culture — board shorts, wax-stained hands, and the salt-bleached dress of ocean-riders worldwide.","era":"c.1950s–present, global","mood":"Salt-bleached, board-waxed, ocean-coded","visual":"Board shorts. Rash guard or wetsuit. Salt-bleached hair. Wax-stained hands. Flip flops. The aesthetic of someone who spends more time in the ocean than on land.","garments":["Board shorts","Rash guard","Flip flops or bare feet","Surf brand T-shirt","Salt-bleached hair"],"habitat":"Surf breaks worldwide, surf communities, surf brand culture.","context":"Surf culture is one of the oldest continuous youth cultures — from Hawaii through 1960s California to global surf tourism, the aesthetic has remained remarkably consistent.","rarity":"Common","see_also":["California Surf","Beach Bum Aesthetic","Surf Luxe"],"colors":["#87CEEB Ocean Blue","#FAF8F5 Foam White","#D4AF37 Sun Gold","#2C5530 Palm Green"],"media":["The Endless Summer (1966) — documentary","North Shore (1987) — film"]},

"California Surf":{"summary":"The specific California surf culture aesthetic — Billabong, Quicksilver, and the Pacific Coast Highway lifestyle packaged as global brand.","era":"c.1960–present, California","mood":"Pacific-Coast, brand-packaged, California-dream","visual":"Surf brands (Billabong, Quicksilver, Rip Curl). Board shorts in California-specific prints. Vintage VW van. The specific California-ness of surf culture — blonde, tanned, and Pacific.","garments":["Billabong or Quicksilver","California-print board shorts","Surf brand hoodie","Flip flops","VW van as accessory"],"habitat":"California coast, surf culture globally, California-dream brand world.","context":"California surf culture was packaged and exported globally through brands like Billabong and Quicksilver — the Beach Boys made it the American dream before hippies made it the counterculture.","rarity":"Common","see_also":["Surf Aesthetic","Beach Bum Aesthetic","Z-Boys Aesthetic"],"colors":["#87CEEB Pacific Blue","#D4AF37 California Gold","#FAF8F5 Surf White","#FF6B6B Sunset Pink"],"media":["The Endless Summer (1966) — documentary","Point Break (1991) — film"]},

"Beach Bum Aesthetic":{"summary":"The deliberately unambitious, sand-between-toes, permanent-vacation dress of the beach lifestyle taken to its logical conclusion.","era":"c.1960s–present","mood":"Permanently vacationing, sand-between-toes, ambition-free","visual":"Board shorts as daily wear. No shoes. T-shirt optional. The aesthetic of someone who has chosen beach life over career — permanently tanned, permanently sandy, permanently relaxed.","garments":["Board shorts as daily wear","No shoes","Optional T-shirt","Sun-faded everything","Sand in everything"],"habitat":"Beach towns globally, surf bum culture, permanent vacation communities.","context":"Beach Bum is the surf aesthetic taken to its logical conclusion — the permanent vacation as life choice. It is both aspirational (freedom) and cautionary (sunburn).","rarity":"Niche","see_also":["Surf Aesthetic","California Surf","Island Hopper Aesthetic"],"colors":["#D4AF37 Sand Gold","#87CEEB Ocean Blue","#FAF8F5 Bleached White","#C1440E Sunburn"],"media":["The Big Lebowski (1998) — film","Forgetting Sarah Marshall (2008) — film"]},

"Surf Luxe":{"summary":"The high-end fashion interpretation of surf culture — luxury beachwear, designer board shorts, and the beach as runway.","era":"c.2010–present","mood":"Luxury-beached, designer-surfed, premium-coastal","visual":"Designer beachwear. Quality linen. Expensive sandals. The aesthetic of someone who surfs but can also afford the beachfront property. Luxury resort wear meets genuine surf culture.","garments":["Designer board shorts","Quality linen shirt","Expensive leather sandals","Premium sunglasses","Luxury beach accessories"],"habitat":"Luxury beach resorts, Malibu, Byron Bay, high-end surf culture.","context":"Surf Luxe represents the gentrification of surf culture — when beachfront property costs millions, the surf aesthetic gets expensive. Brands like Orlebar Brown and Frescobol Carioca target this market.","rarity":"Niche","see_also":["Surf Aesthetic","Resort Wear","Coastal Athletic"],"colors":["#87CEEB Luxury Blue","#FAF8F5 Linen White","#D4AF37 Premium Gold","#8B7355 Sandal Tan"],"media":["Surf luxe brand campaigns — fashion"]},

"Modern Surf":{"summary":"The contemporary, sustainably-minded, diverse surf culture — beyond the blonde California stereotype into global, inclusive surfing.","era":"c.2010–present","mood":"Sustainably diverse, beyond-stereotype, globally inclusive","visual":"Sustainable surf brands. Diverse representation. Technical fabrics. The evolution of surf aesthetic beyond the blonde-and-tanned California stereotype into a global, gender-diverse, environmentally conscious culture.","garments":["Sustainable surf brand","Technical recycled-fabric wetsuit","Inclusive surf fashion","Gender-neutral board shorts","Eco-conscious accessories"],"habitat":"Contemporary surf communities, sustainable surf brands, diverse surf culture.","context":"Modern Surf represents surf culture's overdue diversification — women's surfing, Black surfing, and non-Western surf cultures are finally receiving recognition and shaping the aesthetic beyond its Californian origins.","rarity":"Common","see_also":["Surf Aesthetic","Sustainable Fashion Aesthetic","Coastal Athletic"],"colors":["#87CEEB Ocean Blue","#2C5530 Eco Green","#FAF8F5 Clean White","#8B7355 Natural"],"media":["Bethany Hamilton documentary — documentary","Modern surf documentation"]},

"Coastal Athletic":{"summary":"The fitness-meets-beach visual culture — running on the boardwalk, surfing at dawn, and the athletic-coastal lifestyle as aesthetic category.","era":"c.2015–present","mood":"Beach-athletic, boardwalk-running, dawn-surfing","visual":"Athletic wear in coastal colours. Running shoes with beach proximity. The visual overlap between fitness culture and beach lifestyle — morning surf followed by a run on the boardwalk.","garments":["Athletic wear in coastal colours","Quality running shoes","Beach-athletic hybrid","Surf-fitness crossover","Performance beachwear"],"habitat":"Coastal fitness communities, beach-adjacent athletic culture, Bondi to Bronte walk aesthetic.","context":"Coastal Athletic merges two contemporary lifestyle aesthetics — fitness culture and beach culture — into a single visual identity. It is as much about Instagram content as actual exercise.","rarity":"Common","see_also":["Surf Aesthetic","Athleisure","Runner's Aesthetic"],"colors":["#87CEEB Coastal Blue","#FAF8F5 Athletic White","#D4AF37 Sand Gold","#2C5530 Sea Green"],"media":["Coastal athletic content — social media"]},

// ═══════════════════════════════════════════════════════════════════
// POLITICAL & IDEOLOGICAL SUBCULTURES
// ═══════════════════════════════════════════════════════════════════

"Suffragette Dress":{"summary":"The politically coded dress of the women's suffrage movement — purple, white, and green, and the first modern use of fashion as coordinated political communication.","era":"c.1908–1918, Britain and America","mood":"Politically coded, dignified-militant, colour-coordinated","visual":"Ordinary Edwardian dress in suffragette colours: purple (dignity), white (purity), green (hope). WSPU badges and sashes. Deliberately respectable appearance to counter 'unsexed woman' attacks.","garments":["Purple, white, green colour coding","WSPU enamel badge","Suffragette sash","Respectable Edwardian outfit","Political banner"],"habitat":"Suffrage history, women's rights heritage, feminist fashion history.","context":"The suffragette colour code was a sophisticated communication system — women could identify as supporters without carrying signs. The WSPU's use of fashion as propaganda was pioneering.","rarity":"Extinct","see_also":["Women's Liberation Fashion","Civil Rights Movement Fashion","Protest Fashion"],"colors":["#6B2D8A Dignity Purple","#FAF8F5 Purity White","#4A7C59 Hope Green"],"media":["Suffragette (2015) — film","Pankhurst documentary"]},

"Socialist Realism Fashion":{"summary":"The heroic-worker, state-designed, ideology-as-dress aesthetic of Soviet and communist states — when fashion was central planning.","era":"c.1932–1991, Soviet bloc","mood":"State-designed, worker-heroic, centrally planned","visual":"Standardised work clothing. Military-influenced cuts. Muted colours. The deliberate absence of fashion trends as ideological statement — everyone dressed the same because the state made the clothes.","garments":["Standardised work clothing","Military-influenced jacket","Muted colour palette","State-issued shoes","No fashion variation"],"habitat":"Soviet history, communist-era cultural exhibits, Cold War fashion history.","context":"Socialist Realism applied to fashion meant state-controlled production — individual expression through dress was bourgeois. The gap between party propaganda (heroic workers in neat uniforms) and reality (chronic shortages) was enormous.","rarity":"Extinct","see_also":["Constructivist Fashion","Mao Suit Aesthetic","Union Workwear Aesthetic"],"colors":["#8B0000 Soviet Red","#2C5530 Military Green","#5B5B5B Worker Grey","#8B7355 Khaki"],"media":["Soviet propaganda posters — art","Goodbye, Lenin! (2003) — film"]},

"Union Workwear Aesthetic":{"summary":"The blue-collar, union-proud, work-clothes-as-political-identity dress of organised labour — the dignity of work made visible.","era":"c.1880–present","mood":"Union-proud, work-dignified, collectively dressed","visual":"Work clothes worn with union pride — union badge, union cap, union jacket. The specific dignity of clean work clothing maintained despite physical labour.","garments":["Union badge on work jacket","Clean maintained work clothes","Union cap","Steel-toed boots","Simple functional workwear"],"habitat":"Union halls, labour movement heritage, Workers' Memorial Day.","context":"Union workwear represents the political identity of organised labour — the badge, the cap, and the maintained work clothes are statements about the dignity of labour and the importance of collective action.","rarity":"Niche","see_also":["Frontier Workwear Aesthetic","Rugged Americana","Protest Fashion"],"colors":["#1B4F72 Union Blue","#8B7355 Work Brown","#FAF8F5 Clean White","#D4AF37 Badge Gold"],"media":["Norma Rae (1979) — film","Made in Dagenham (2010) — film"]},

"Civil Rights Movement Fashion":{"summary":"The deliberate, dignified, Sunday-best dress of the American civil rights movement — when dressing well was an act of political resistance.","era":"c.1955–1968, United States","mood":"Deliberately dignified, resistance-dressed, Sunday-best political","visual":"Sunday best: men in suits and ties, women in dresses and gloves. The deliberate presentation of dignity and respectability in the face of violent racism. Martin Luther King Jr.'s suit as political armour.","garments":["Sunday-best suit and tie","Formal dress and gloves","Church-appropriate hat","Dignified formal shoes","NAACP or SCLC badge"],"habitat":"Civil rights heritage, MLK commemorations, African American history. SENSITIVE: This aesthetic represents dress in the context of violent racist oppression.","context":"Civil rights protesters deliberately dressed in their Sunday best as a political strategy — presenting irreproachable dignity to cameras documenting white supremacist violence. The suit was armour; the dress was resistance.","rarity":"Extinct","see_also":["Harlem Renaissance Fashion","Black Girl Magic Fashion","Protest Fashion"],"colors":["#1A1A1A Formal Black","#FAF8F5 Sunday White","#D4AF37 Badge Gold","#1B4F72 Dignity Blue"],"media":["Selma (2014) — film","Eyes on the Prize (documentary) — documentary"]},

"Black Panther Aesthetic":{"summary":"The revolutionary visual identity of the Black Panther Party — black leather jackets, black berets, and the most iconic political uniform of the 1960s.","era":"c.1966–1982, United States","mood":"Militantly revolutionary, beret-crowned, Black-power visual","visual":"Black leather jacket. Black beret. Black trousers. Black turtleneck. Sunglasses. The deliberately military-influenced uniform designed by Huey Newton and Bobby Seale to project power and discipline.","garments":["Black leather jacket","Black beret","Black turtleneck","Sunglasses","Black trousers"],"habitat":"Black Panther history, Black power heritage, revolutionary politics. SENSITIVE: The Black Panther Party was subject to violent state repression including assassination.","context":"The Black Panther uniform was deliberately designed to project military discipline and Black power. The FBI under COINTELPRO specifically targeted the Party. The aesthetic remains one of the most powerful political visual identities in American history.","rarity":"Extinct","see_also":["Civil Rights Movement Fashion","Blaxploitation Aesthetic","Revolutionary Fashion"],"colors":["#1A1A1A Panther Black","#2C2C2C Leather","#D4AF37 Power Gold","#8B0000 Revolutionary Red"],"media":["The Black Panthers: Vanguard of the Revolution (2015) — documentary","Judas and the Black Messiah (2021) — film"]},

"Women's Liberation Fashion":{"summary":"The bra-burning, consciousness-raising, practical dress of the women's liberation movement — when women stopped dressing for the male gaze.","era":"c.1968–1980","mood":"Liberation-dressed, male-gaze-refusing, practically feminist","visual":"Practical, comfortable clothing. Jeans and T-shirts. No bra (or choosing to wear one freely). No makeup or minimal. The deliberate refusal to dress for male approval. Dungarees as feminist statement.","garments":["Comfortable practical jeans","Feminist slogan T-shirt","Dungarees","No or minimal makeup","Sensible shoes"],"habitat":"Feminist history, women's liberation heritage, consciousness-raising groups.","context":"The 'bra-burning' image is largely myth — at the 1968 Miss America protest, women threw bras into a 'freedom trash can' but didn't burn them. The broader aesthetic of refusing to dress for men was real and revolutionary.","rarity":"Extinct","see_also":["Suffragette Dress","Riot Grrrl","Protest Fashion"],"colors":["#7B68EE Feminist Purple","#FAF8F5 White","#4A7C59 Green","#1B4F72 Denim Blue"],"media":["She's Beautiful When She's Angry (2014) — documentary","Gloria: In Her Own Words (documentary)"]},

"Anarchist Aesthetic":{"summary":"The circle-A, black-bloc, deliberately anti-state visual identity of anarchist politics — punk's politics without punk's fashion.","era":"c.1880–present","mood":"Anti-state, circle-A coded, deliberately uncommercial","visual":"Black clothing (for black bloc actions). Circle-A symbol. DIY and second-hand. Anti-brand. The deliberate visual rejection of consumer capitalism applied to dress.","garments":["All-black clothing","Circle-A patches or badges","DIY second-hand clothing","Anti-brand presentation","Functional protest wear"],"habitat":"Anarchist communities, direct action events, autonomous spaces.","context":"Anarchist fashion is deliberately anti-fashion — any visual identity that becomes a brand contradicts the ideology. The black bloc tactic (all-black, face-covered) is both practical and philosophical.","rarity":"Niche","see_also":["Crass Aesthetic","Anarcho-Punk","Protest Fashion"],"colors":["#1A1A1A Anarcho Black","#8B0000 Red","#FAF8F5 White","#5B5B5B Grey"],"media":["Anarchist history documentaries","Punk Is Dead, Penny Rimbaud — book"]},

"Revolutionary Fashion":{"summary":"The visual vocabulary of political revolution — from the Phrygian cap to the Che Guevara T-shirt, the dress of those who want to change the world.","era":"c.1789–present","mood":"World-changing, symbolically charged, revolution-coded","visual":"Each revolution creates its own visual identity — the Phrygian cap (France 1789), the Che beret (Cuba 1959), the keffiyeh (Palestinian resistance). Revolutionary dress is always symbolic and specific.","garments":["Revolution-specific symbol","Political sash or badge","Symbolic headwear","Propaganda T-shirt","Solidarity accessories"],"habitat":"Revolutionary movements globally, political solidarity events.","context":"Every revolution invents its own fashion — the visual identity is as important as the manifesto. The Che Guevara T-shirt is the most reproduced revolutionary image in commercial history, which is itself a contradiction.","rarity":"Niche","see_also":["French Revolutionary Dress","Black Panther Aesthetic","Protest Fashion"],"colors":["#8B0000 Revolutionary Red","#1A1A1A Black","#FAF8F5 White","#D4AF37 Gold"],"media":["Che (2008) — film","Revolutionary history documentaries"]},

"Protest Fashion":{"summary":"The practical, visible, politically communicative dress of street protest — from suffragette sashes to BLM T-shirts, the wardrobe of dissent.","era":"c.1900–present","mood":"Visibly dissenting, practically communicative, politically dressed","visual":"Slogan T-shirts. Political badges. Practical protest clothing — comfortable shoes for marching, layers for weather. The specific visual grammar of making political beliefs visible.","garments":["Political slogan T-shirt","Protest badge or pin","Comfortable marching shoes","Weather-appropriate layers","Solidarity accessory"],"habitat":"Protests and marches worldwide, political movements.","context":"Protest fashion serves dual functions — communicating political beliefs and being practical for hours of marching. The slogan T-shirt is the 21st century's most democratic political garment.","rarity":"Common","see_also":["Suffragette Dress","Civil Rights Movement Fashion","Activist Dress"],"colors":["#1A1A1A Protest Black","#8B0000 Red","#FAF8F5 White","#2C5530 Green"],"media":["Protest footage worldwide — cultural"]},

"Activist Dress":{"summary":"The everyday, sustained political dressing beyond single protests — the wardrobe of someone whose politics are visible in their daily clothing choices.","era":"c.1960s–present","mood":"Sustainedly political, everyday-visible, values-dressed","visual":"Ethical and sustainable clothing choices. Political badges worn daily. Fair-trade and union-made preferences. The sustained daily practice of dressing one's values.","garments":["Ethical brand clothing","Daily political badge","Fair-trade accessories","Sustainable wardrobe choices","Political T-shirt for everyday"],"habitat":"Activist communities, ethical fashion, political everyday life.","context":"Activist Dress represents the sustained daily practice of political dressing — beyond the single protest, into everyday choices about where clothes come from and what they communicate.","rarity":"Niche","see_also":["Protest Fashion","Eco-Activist Fashion","Sustainable Fashion Aesthetic"],"colors":["#2C5530 Eco Green","#1A1A1A Black","#FAF8F5 White","#D4AF37 Badge Gold"],"media":["True Cost (2015) — documentary","Fashion activism content"]},

"Anti-Fashion Aesthetic":{"summary":"The deliberate, ideological rejection of fashion as a system — wearing whatever negates the fashion industry's demands.","era":"c.1960s–present","mood":"Ideologically rejecting, system-refusing, anti-trend","visual":"Whatever fashion currently demands, do the opposite. Oversized when slim is in. Plain when decorated is in. The deliberate, considered rejection of fashion trends as ideological position.","garments":["Deliberately anti-trend clothing","Plain functional garments","Second-hand or repaired","No brand signifiers","Anti-fashion as position"],"habitat":"Anti-fashion communities, Comme des Garçons adjacent, ideological fashion refusal.","context":"Anti-Fashion is fashion's permanent shadow — every trend generates its refusal. Comme des Garçons and Martin Margiela made anti-fashion into high fashion, which is anti-fashion's permanent paradox.","rarity":"Niche","see_also":["Normcore","Crass Aesthetic","Anarchist Aesthetic"],"colors":["#5B5B5B Anti Grey","#1A1A1A Anti Black","#8B7355 Anti Brown","#FAF8F5 Anti White"],"media":["Comme des Garçons retrospective — exhibition","The True Cost (2015) — documentary"]},

"Eco-Activist Fashion":{"summary":"The specifically environmental-activist dress — natural materials, protest slogans, and the visual language of climate justice.","era":"c.1990–present","mood":"Environmentally active, natural-material, climate-just","visual":"Natural and sustainable materials. Environmental slogan T-shirts. Practical outdoor clothing for protests and direct action. The intersection of environmental values and fashion choices.","garments":["Sustainable natural-material clothing","Environmental slogan T-shirt","Practical outdoor protest wear","Recycled-material accessories","Eco-branded clothing"],"habitat":"Environmental protest movements, climate activism, Extinction Rebellion, Greenpeace.","context":"Eco-Activist Fashion represents the fashion expression of environmental politics — wearing natural materials and sustainable brands as daily practice, dressing for climate protests as regular activity.","rarity":"Niche","see_also":["Sustainable Fashion Aesthetic","Protest Fashion","Solarpunk"],"colors":["#2C5530 Earth Green","#8B7355 Natural Brown","#FAF8F5 Clean White","#87CEEB Sky Blue"],"media":["Extinction Rebellion documentation — cultural","The True Cost (2015) — documentary"]},

"Antifa Aesthetic":{"summary":"The black-bloc, face-covered, deliberately anonymous visual identity of anti-fascist direct action.","era":"c.1930s–present","mood":"Anonymously militant, face-covered, anti-fascist","visual":"All black. Face covering. The deliberate visual anonymity of anti-fascist direct action — the black bloc is both tactical (avoiding identification) and symbolic (collective over individual).","garments":["All-black clothing","Face covering","Black bloc uniform","Sturdy boots","No identifying features"],"habitat":"Anti-fascist direct action, anti-fascist communities. SENSITIVE: Anti-fascist action involves physical confrontation and is politically contested.","context":"Antifa's visual identity is deliberately anti-individual — the all-black, face-covered bloc is designed to prevent identification by authorities and far-right groups. The aesthetic is tactical before it is fashionable.","rarity":"Niche","see_also":["Anarchist Aesthetic","Black Panther Aesthetic","Protest Fashion"],"colors":["#1A1A1A Bloc Black","#8B0000 Anti-Fascist Red","#FAF8F5 Banner White","#5B5B5B Street Grey"],"media":["Antifa: A Look at the Anti-Fascist Movement (documentary)","Political documentation"]}

};
